#  Introduction to Numerical Computing

## Functions

In [21]:
def my_function():
  print("Hello from a function")

In [22]:
def my_function():
  print("Hello from a function")

my_function()

Hello from a function


def my_function(fname):
  print(fname + " Refsnes")

my_function("Emil")
my_function("Tobias")
my_function("Linus")

## Number of Arguments
By default, a function must be called with the correct number of arguments. Meaning that if your function expects 2 arguments, you have to call the function with 2 arguments, not more, and not less.

In [23]:
def my_function(fname, lname):
  print(fname + " " + lname)

my_function("Emil", "Refsnes")

Emil Refsnes


## Arbitrary Arguments, *args
If you do not know how many arguments that will be passed into your function, add a * before the parameter name in the function definition.

This way the function will receive a tuple of arguments, and can access the items accordingly:

In [24]:
def my_function(*kids):
  print("The youngest child is " + kids[2])

my_function("Emil", "Tobias", "Linus")

The youngest child is Linus


##Keyword Arguments
You can also send arguments with the key = value syntax.

This way the order of the arguments does not matter.

In [26]:
def my_function(child3, child2, child1):
  print("The youngest child is " + child3)

my_function(child1 = "Emil", child2 = "Tobias", child3 = "Linus")

The youngest child is Linus


## Arbitrary Keyword Arguments, **kwargs
If you do not know how many keyword arguments that will be passed into your function, add two asterisk: ** before the parameter name in the function definition.

In [27]:
def my_function(**kid):
  print("His last name is " + kid["lname"])

my_function(fname = "Tobias", lname = "Refsnes")

His last name is Refsnes


## Default Parameter Value
The following example shows how to use a default parameter value.

If we call the function without argument, it uses the default value:

In [28]:
def my_function(country = "Norway"):
  print("I am from " + country)

my_function("Sweden")
my_function("India")
my_function()
my_function("Brazil")

I am from Sweden
I am from India
I am from Norway
I am from Brazil


## Passing a List as an Argument
You can send any data types of argument to a function (string, number, list, dictionary etc.), and it will be treated as the same data type inside the function.

In [29]:
def my_function(food):
  for x in food:
    print(x)

fruits = ["apple", "banana", "cherry"]

my_function(fruits)

apple
banana
cherry


## Return Values

In [30]:
def my_function(x):
  return 5 * x

print(my_function(3))
print(my_function(5))
print(my_function(9))

15
25
45


# Why NumPy?

#  Installing and Importing

In [31]:
import numpy as np

# Creating Arrays

In [32]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


# Array Operations

In [33]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5 7 9]
print(a * b)  # [4 10 18]

[5 7 9]
[ 4 10 18]


# Useful NumPy Functions

In [34]:
nums = np.array([10, 20, 30, 40, 50])
print(np.mean(nums))  # average
print(np.max(nums))   # maximum
print(np.min(nums))   # minimum
print(np.std(nums))   # standard deviation

30.0
50
10
14.142135623730951


# Multi-Dimensional Arrays

In [35]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix.shape)  # (2, 2)
print(matrix[0, 1])  # 2

(2, 2)
2


# Generating Arrays Automatically

In [36]:
print(np.zeros((2, 3)))   # 2x3 array of zeros
print(np.ones((3, 3)))    # 3x3 array of ones
print(np.arange(0, 10, 2)) # 0 to 10 step 2
print(np.random.rand(3, 3)) # random numbers

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[[0.48534406 0.26566076 0.07425822]
 [0.57917515 0.55320277 0.22527361]
 [0.08364124 0.14751453 0.7483581 ]]


# Real Example: Daily Temperatures

In [37]:
temps = np.array([29.5, 30.1, 28.9, 31.0, 29.8])
print("Average Temp:", np.mean(temps))
print("Max Temp:", np.max(temps))
print("Min Temp:", np.min(temps))

Average Temp: 29.860000000000003
Max Temp: 31.0
Min Temp: 28.9


# In-Class Activity

# Common Mistakes

# Key Takeaways

# Homework