#  Introduction to Numerical Computing

# Why NumPy?

#  Installing and Importing

In [1]:
import numpy as np

# Creating Arrays

In [2]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


# Array Operations

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5 7 9]
print(a * b)  # [4 10 18]

[5 7 9]
[ 4 10 18]


# Useful NumPy Functions

In [4]:
nums = np.array([10, 20, 30, 40, 50])
print(np.mean(nums))  # average
print(np.max(nums))   # maximum
print(np.min(nums))   # minimum
print(np.std(nums))   # standard deviation

30.0
50
10
14.142135623730951


# Multi-Dimensional Arrays

In [5]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix.shape)  # (2, 2)
print(matrix[0, 1])  # 2

(2, 2)
2


# Generating Arrays Automatically

In [6]:
print(np.zeros((2, 3)))   # 2x3 array of zeros
print(np.ones((3, 3)))    # 3x3 array of ones
print(np.arange(0, 10, 2)) # 0 to 10 step 2
print(np.random.rand(3, 3)) # random numbers

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[[0.76950094 0.70907584 0.29207037]
 [0.3493608  0.61390032 0.37027208]
 [0.6639354  0.88436811 0.43092934]]


# Real Example: Daily Temperatures

In [7]:
temps = np.array([29.5, 30.1, 28.9, 31.0, 29.8])
print("Average Temp:", np.mean(temps))
print("Max Temp:", np.max(temps))
print("Min Temp:", np.min(temps))

Average Temp: 29.860000000000003
Max Temp: 31.0
Min Temp: 28.9


# In-Class Activity

# Common Mistakes

# Key Takeaways

# Homework